import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Featured from '@/components/Featured'
import PizzaList from '@/components/PizzaList'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Food Ordering App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:ital,wght@0,200;0,300;0,400;0,500;0,600;0,700;1,700&display=swap" rel="stylesheet"></link>
      </Head>
      <Featured></Featured>
      <PizzaList></PizzaList>
    </>
  )
}
